CREATE DATABASE GameBacklog;

USE GameBacklog;

CREATE TABLE Games(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL UNIQUE,
    State INT NOT NULL,
    ImageSource VARCHAR(100) NOT NULL UNIQUE,
    PlayStation BOOLEAN NOT NULL DEFAULT FALSE,
    PlayStation2 BOOLEAN NOT NULL DEFAULT FALSE,
    PlayStation3 BOOLEAN NOT NULL DEFAULT FALSE,
    PlayStation4 BOOLEAN NOT NULL DEFAULT FALSE,
    PSP BOOLEAN NOT NULL DEFAULT FALSE,
    GameboyAdvance BOOLEAN NOT NULL DEFAULT FALSE,
    NintendoDS BOOLEAN NOT NULL DEFAULT FALSE,
    Nintendo3DS BOOLEAN NOT NULL DEFAULT FALSE,
    NintendoSwitch BOOLEAN NOT NULL DEFAULT FALSE,
    XboxOne BOOLEAN NOT NULL DEFAULT FALSE,
    PC BOOLEAN NOT NULL DEFAULT FALSE,
    Blizzard BOOLEAN NOT NULL DEFAULT FALSE,
    Epic BOOLEAN NOT NULL DEFAULT FALSE,
    Origin BOOLEAN NOT NULL DEFAULT FALSE,
    Steam BOOLEAN NOT NULL DEFAULT FALSE,
    Twitch BOOLEAN NOT NULL DEFAULT FALSE,
    UPlay BOOLEAN NOT NULL DEFAULT FALSE,
    Microsoft BOOLEAN NOT NULL DEFAULT FALSE
);